# See PwnPlantGrowth's page on http://dev.bukkit.org for more config details.

# Full biome list available at http://jd.bukkit.org/dev/apidocs/org/bukkit/block/Biome.html

# Plants / Crops are available in the "Material" list. See the following for official material names.
# Full material list available at http://jd.bukkit.org/rb/apidocs/org/bukkit/Material.html

# Which worlds should this plugin be enabled in? Worlds not in this list will have default growth.
enabled_worlds:
  - world
  - world_nether
  - world_end

# Stop buckets and dispensers from transporting source blocks - adds realism.
block_water_bucket: false
block_water_dispenser: false
    
# Natural sky light level: 0 allows any, 10 is sunlight through glass/tree leaves, 15 is direct sunlight
min_natural_light: 0

# List of items allowed to grow in false light (torches, lightstone, lava) - use offical MATERIAL names to add to this list
grow_in_dark: 
  - RED_MUSHROOM
  - BROWN_MUSHROOM
  - NETHER_WARTS
  - COCOA 
  - CACTUS
  - CARROT
  - CROPS
  - MELON_BLOCK
  - MELON_STEM
  - POTATO
  - PUMPKIN_BLOCK
  - PUMPKIN_STEM
  - SUGAR_CANE_BLOCK
  - ACACIA
  - BIG_TREE
  - BIRCH
  - COCOA_TREE
  - DARK_OAK
  - JUNGLE
  - JUNGLE_BUSH
  - MEGA_REDWOOD
  - REDWOOD
  - SMALL_JUNGLE
  - SWAMP
  - TALL_BIRCH
  - TALL_REDWOOD
  - TREE

# Enable use of weed killer
weed_killer_enabled: false

# A Block that can act as a weed killer (keeps plants from dying, will NOT affect growth rates)
weed_killer: GOLD_BLOCK

# Radius that weed killer protects, plants within this distance of the weed killer block will not turn to dead shrubs
weed_killer_radius: 5

# Enable use of fertilizer
fertilizer_enabled: false

# A Block that can act as a fertilizer (keeps plants growing at 100% - as long as they are in the right biome)
fertilizer: SOUL_SAND

# Radius that fertilizer affects, plants within this distance of the block will grow at 100%
fertilizer_radius: 5

# Enable use of UV Light Block
uv_enabled: false

# A Block that can act as UV Light (will allow plants in radius to grow where there is no natural light, -note, still requires actual lighting)
uv: GLOWSTONE

# Radius that UV affects
uv_radius: 5

# Run a debug log to view additional plugin data for troubleshooting and configuration, turn off in production!
debug_log: false

# CROPS - Important note, as of PPG 1.6 the plant names are now all in UPPER CASE matching the actual Bukkit Material.TYPE 

CACTUS:
    Growth: 25
    GrowthDark: 15
    Death: 0
    DeathDark: 2
    Biome: [] 
    DESERT: 
      Growth: 50
      Death: 0 

CARROT: 
    Growth: 25
    GrowthDark: 15
    Death: 0
    DeathDark: 2    
    Biome: [] 

    PLAINS: 
      Growth: 30

      Death: 0 

    DESERT:
      Growth: 15
      GrowthDark: 10
      Death: 0

COCOA: 
    Growth: 25
    Death: 0
    Biome: []
    JUNGLE: 
      Growth: 50
      Death: 0 

    JUNGLE_HILLS:
      Growth: 50
      Death: 0 

MELON_BLOCK: 
    Growth: 15
    Death: 0
    JUNGLE: 
      Growth: 25
      Death: 0 
    JUNGLE_HILLS:
      Growth: 25
      Death: 0 

MELON_STEM:
    Growth: 50
    Death: 0
    Biome: []

NETHER_WARTS:
    Growth: 15
    Death: 0
    Biome: []
    HELL: 
      Growth: 50
      Death: 0     

POTATO:
    Growth: 25
    Death: 0
    DeathDark: 2  
    Biome: []

PUMPKIN_BLOCK:
    Growth: 15
    Death: 0   
    Biome: []

PUMPKIN_STEM:
    Growth: 50
    Death: 0
    Biome: []
    
SUGAR_CANE_BLOCK:
    Growth: 20
    Death: 0
    DeathDark: 1  
    Biome: [] 
    BEACH: 
      Growth: 30
      Death: 0 
    RIVER:
      Growth: 35
      Death: 0
    SWAMPLAND:
      Growth: 35
      Death: 0          

# This is WHEAT - In this example wheat will grow everywhere at 50% rate, except plains it will grow at %100
CROPS:
    Growth: 25
    Death: 0
    DeathDark: 1  
    Biome: []
    PLAINS: 
      Growth: 30
      Death: 0 
      
# TREES 
# Full tree list available at http://jd.bukkit.org/dev/apidocs/org/bukkit/TreeType.html

ACACIA:
    Growth: 50
    Death: 0
    Biome: [] 

BIRCH:
    Growth: 50
    Death: 0
    Biome: []

TALL_BIRCH:
    Growth: 50
    Death: 0
    Biome: []
    
JUNGLE:
    Growth: 10
    Death: 0
    Biome: []
    JUNGLE: 
      Growth: 50
    JUNGLE_HILLS:
      Growth: 50
    JUNGLE_EDGE: 
      Growth: 50
    JUNGLE_EDGE_MOUNTAINS:
      Growth: 50
    JUNGLE_MOUNTAINS:
      Growth: 50 

JUNGLE_BUSH:
    Growth: 50
    Biome: []
    JUNGLE: 
      Growth: 50
    JUNGLE_HILLS:
      Growth: 50


    JUNGLE_EDGE: 
      Growth: 50
    JUNGLE_EDGE_MOUNTAINS:
      Growth: 50
    JUNGLE_MOUNTAINS:
      Growth: 50   

SMALL_JUNGLE:
    Growth: 50
    Death: 0
    Biome: []
    JUNGLE: 
      Growth: 50
    JUNGLE_HILLS:
      Growth: 50
    JUNGLE_EDGE: 
      Growth: 50
    JUNGLE_EDGE_MOUNTAINS:
      Growth: 50
    JUNGLE_MOUNTAINS:
      Growth: 50 
    
DARK_OAK:
    Growth: 50
    Death: 0
    Biome: [] 

REDWOOD:
    Growth: 50
    Death: 0
    Biome: [] 

TALL_REDWOOD:
    Growth: 50
    Death: 0
    Biome: [] 

MEGA_REDWOOD:
    Growth: 50
    Death: 0
    Biome: []   
    
SWAMP:
    Growth: 50
    Death: 0
    Biome: []
        
TREE:
    Growth: 50
    Death: 0
    Biome: []

BIG_TREE:
    Growth: 50
    Death: 0
    Biome: []

COCOA_TREE:
    Growth: 50
    Death: 0
    Biome: []
    
# GIANT MUSHROOMS
BROWN_MUSHROOM:
    Growth: 80
    Death: 0
    Biome: [] 

RED_MUSHROOM:
    Growth: 80
    Death: 0
    Biome: [] 

      
# Plugin will check for the following list of plants as of ver. 2.1.1 
# "CACTUS", "CARROT", "COCOA", "CROPS", "MELON_BLOCK", "MELON_STEM", "NETHER_WARTS", "POTATO", "PUMPKIN_BLOCK", "PUMPKIN_STEM", "SUGAR_CANE_BLOCK", "ACACIA", "BIG_TREE", "BIRCH", "BROWN_MUSHROOM", "COCOA_TREE", "DARK_OAK", "JUNGLE", "JUNGLE_BUSH", "MEGA_REDWOOD", "RED_MUSHROOM", "REDWOOD", "SMALL_JUNGLE", "SWAMP", "TALL_BIRCH", "TALL_REDWOOD", "TREE"